export interface MediaAsset {
  id: string;
  title: string;
  subTitle: string;
  badge: string;
  description: string;
  category: 'wealth' | 'support' | 'corporate' | 'security' | 'offices' | 'videos';
  bgImage: string;
  hexColor: string;
  cta: string;
  link: string;
}

export const BANKING_MEDIA_CATALOG: MediaAsset[] = [
  // CATEGORY: WEALTH (Premium Wealth & Private Banking) - 18 assets
  {
    id: 'asset-wealth-1',
    title: 'Swiss Reserve Vaults',
    subTitle: 'Elite Custodian Ledger',
    badge: 'Swiss Reserve',
    description: 'Bespoke high-security multi-currency private safety compartments nested in secure offshore Zurich banking bays.',
    category: 'wealth',
    bgImage: 'https://images.unsplash.com/photo-1563013544-824ae1d704d3?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#D4AF37',
    cta: 'Browse Reserves',
    link: '/summary'
  },
  {
    id: 'asset-wealth-2',
    title: 'Solid Gold Bullion',
    subTitle: 'Physical Capital Anchor',
    badge: '99.9% Purity',
    description: 'Direct physical gold allocation. Sourced from London Bullion Market Association (LBMA) accredited refineries.',
    category: 'wealth',
    bgImage: 'https://images.unsplash.com/photo-1610375461246-83df859d8222?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#fbbf24',
    cta: 'Allocate Gold',
    link: '/settings'
  },
  {
    id: 'asset-wealth-3',
    title: 'Elite Advisor Portfolios',
    subTitle: 'Personal Asset Strategy',
    badge: 'Private Advisory',
    description: 'Expert cross-border trust structuring, generational inheritance formulation, and premium offshore asset protection planning.',
    category: 'wealth',
    bgImage: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#6366f1',
    cta: 'Contact Advisor',
    link: '/advisor'
  },
  {
    id: 'asset-wealth-4',
    title: 'Bespoke Marine Wealth',
    subTitle: 'Lifestyle Investment Pool',
    badge: 'Luxe Assets',
    description: 'Sovereign structured finance options backing world-class marine assets, high-value real estate investments, and private fleets.',
    category: 'wealth',
    bgImage: 'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#0ea5e9',
    cta: 'View Fleet Pool',
    link: '/summary'
  },
  {
    id: 'asset-wealth-5',
    title: 'Sovereign Gateway Lounge',
    subTitle: 'First Class Airport Access',
    badge: 'VIP Club Lounge',
    description: 'Complementary, unrestricted private jet terminal clearance and global luxury airport suites for sovereign card holders.',
    category: 'wealth',
    bgImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#f43f5e',
    cta: 'Activate Lounge',
    link: '/cards'
  },
  {
    id: 'asset-wealth-6',
    title: 'Heavy Metallic Card',
    subTitle: 'Pure Titanium Card',
    badge: 'Sovereign Mint',
    description: 'Engineered from military-grade titanium composite. Offers ultimate zero-discretion limits and strict transactional confidentiality.',
    category: 'wealth',
    bgImage: 'https://images.unsplash.com/photo-1559445375-c2f70b2a29c7?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#3b82f6',
    cta: 'Order Card',
    link: '/cards'
  },
  {
    id: 'asset-wealth-7',
    title: 'Private Wealth Sessions',
    subTitle: 'Family Trust Integration',
    badge: 'Bespoke Forum',
    description: 'Direct collaboration desk. Formulate offshore holdings, strategic tax-sheltered vaults, and high-yield estate setups.',
    category: 'wealth',
    bgImage: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#eab308',
    cta: 'Request Forum',
    link: '/advisor'
  },
  {
    id: 'asset-wealth-8',
    title: 'Generational Trusts Office',
    subTitle: 'Inheritance Architecture',
    badge: 'Family Trust',
    description: 'Sophisticated global wealth management aligning cross-border asset transfers with family trust preservation policies.',
    category: 'wealth',
    bgImage: 'https://images.unsplash.com/photo-1542744094-3a31f103e35f?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#a855f7',
    cta: 'Form Trust',
    link: '/settings'
  },
  {
    id: 'asset-wealth-9',
    title: 'Swiss Vault Treasury',
    subTitle: 'Sovereign Bullion Safety',
    badge: 'Vault Reserve',
    description: 'Ultra-secure physical deposit storage for gold bricks, private documents, platinum coins, and legal deeds.',
    category: 'wealth',
    bgImage: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#10b981',
    cta: 'Vault Dashboard',
    link: '/settings'
  },
  {
    id: 'asset-wealth-10',
    title: 'Diamond Custody Escrow',
    subTitle: 'High-Value Safe Keep',
    badge: 'Mineral Escrow',
    description: 'Insured mineral custody locks with dynamic weight-tracking and independent legal certification coordinates.',
    category: 'wealth',
    bgImage: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#ec4899',
    cta: 'Escrow Ledger',
    link: '/summary'
  },
  {
    id: 'asset-wealth-11',
    title: 'Zurich Offshore Advisory',
    subTitle: 'Global Capital Strategy',
    badge: 'Swiss Desk',
    description: 'Premium Swiss-regulated financial structuring targeting dynamic capital growth and tax optimization directives.',
    category: 'wealth',
    bgImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#14b8a6',
    cta: 'Call Swiss Desk',
    link: '/advisor'
  },
  {
    id: 'asset-wealth-12',
    title: 'Private Family Portfolios',
    subTitle: 'Multi-Asset Integration',
    badge: 'Coordinated Trust',
    description: 'Consolidated overview capturing international real-estate holdings, corporate stocks, and raw currency allocations.',
    category: 'wealth',
    bgImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#e0f2fe',
    cta: 'Open Overview',
    link: '/summary'
  },
  {
    id: 'asset-wealth-13',
    title: 'Executive Syndicate Forum',
    subTitle: 'Pre-IPO Buyout Vehicles',
    badge: 'Syndicate Capital',
    description: 'Direct entry into vetted corporate buyouts, technological seed funding, and high-growth retail acquisitions.',
    category: 'wealth',
    bgImage: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#ca8a04',
    cta: 'View Buyouts',
    link: '/summary'
  },
  {
    id: 'asset-wealth-14',
    title: 'Carbon Black Card Elite',
    subTitle: 'Premium Syndicate Card',
    badge: 'Black level',
    description: 'Bespoke carbon-graphite credit cards with fully custom transfer ceilings and 24-hour lifestyle architecture.',
    category: 'wealth',
    bgImage: 'https://images.unsplash.com/photo-1589758438368-0ad531db3366?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#1e293b',
    cta: 'Acquire Card',
    link: '/cards'
  },
  {
    id: 'asset-wealth-15',
    title: 'Sovereign Lobby Entrance',
    subTitle: 'High-Status Lobby Access',
    badge: 'Exclusive Entry',
    description: 'Bespoke marble waiting rooms, private elevators, and offline banking tables strictly reserved for top dignitaries.',
    category: 'wealth',
    bgImage: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#38bdf8',
    cta: 'Schedule Visit',
    link: '/messages'
  },
  {
    id: 'asset-wealth-16',
    title: 'Legal Asset Escrow Seal',
    subTitle: 'Compliant Trust Signing',
    badge: 'Valid Seal',
    description: 'Double-witnessed asset notarisation providing air-tight legal protection templates for major capital transfers.',
    category: 'wealth',
    bgImage: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#10b981',
    cta: 'Inspect Seal',
    link: '/settings'
  },
  {
    id: 'asset-wealth-17',
    title: 'Royal Wealth Treasury',
    subTitle: 'Sovereign Yield Reserve',
    badge: 'Royal Vault',
    description: 'Dedicated institutional vault backing sovereign loans, central bank gold allocations, and international notes.',
    category: 'wealth',
    bgImage: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#84cc16',
    cta: 'Yield Reports',
    link: '/summary'
  },
  {
    id: 'asset-wealth-18',
    title: 'Elite Club Wine Vaults',
    subTitle: 'Alternative High-Yield Assets',
    badge: 'Alternative Tangible',
    description: 'Accredited high-value vintage collections with temperature-monitored blockchain digital custody wrappers.',
    category: 'wealth',
    bgImage: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#f43f5e',
    cta: 'Browse Wine Stock',
    link: '/summary'
  },

  // CATEGORY: SUPPORT (Global Customers & Concierge Support) - 17 assets
  {
    id: 'asset-support-1',
    title: 'Elite Help Desk Desk',
    subTitle: 'Multi-Ethnic Private Support',
    badge: '24/7 Priority',
    description: 'Direct instant access to professional multi-lingual support desks ready to unlock accounts and authorize transfers.',
    category: 'support',
    bgImage: 'https://images.unsplash.com/photo-1521791136368-1a46827d091c?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#6366f1',
    cta: 'Open Live Chat',
    link: '/messages'
  },
  {
    id: 'asset-support-2',
    title: 'Private Relations Manager',
    subTitle: 'Personalized Wealth Support',
    badge: 'Active Liaison',
    description: 'Dedicated financial officer directly assigned to manage your family accounts, business lines, and daily payouts.',
    category: 'support',
    bgImage: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#a855f7',
    cta: 'Meet Lead Manager',
    link: '/advisor'
  },
  {
    id: 'asset-support-3',
    title: 'Helpline Resolution Hub',
    subTitle: 'Instant Sovereign Support',
    badge: 'Priority Dial',
    description: 'Direct encrypted satellite voice pipeline offering zero-wait resolution on high-capital transaction dispatches.',
    category: 'support',
    bgImage: 'https://images.unsplash.com/photo-1549923746-c502d488b3ea?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#ec4899',
    cta: 'Trigger Callback',
    link: '/messages'
  },
  {
    id: 'asset-support-4',
    title: 'Executive Virtual Meeting',
    subTitle: 'Secure Video Call Advisory',
    badge: 'Video Consultation',
    description: 'Scheduled, end-to-end encrypted face-to-face video reviews to discuss major loan requests and strategic asset holds.',
    category: 'support',
    bgImage: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#eab308',
    cta: 'Request Video Call',
    link: '/advisor'
  },
  {
    id: 'asset-support-5',
    title: 'Responsive Dispatch Desk',
    subTitle: 'Real-Time Routing Support',
    badge: 'Support Ledger',
    description: 'Coordinated transaction resolution desk monitoring secure SWIFT and crypto-transfer network clearance loops.',
    category: 'support',
    bgImage: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#10b981',
    cta: 'Inspect Queue',
    link: '/messages'
  },
  {
    id: 'asset-support-6',
    title: 'Personal Investment Partner',
    subTitle: 'Asset Optimization Advisory',
    badge: 'Bespoke Banker',
    description: 'Vetted private banking support to carefully layout custom investment strategies and high-margin yield options.',
    category: 'support',
    bgImage: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#0ea5e9',
    cta: 'Consult Partner',
    link: '/advisor'
  },
  {
    id: 'asset-support-7',
    title: 'Senior Portfolio Advisor',
    subTitle: 'Global Trade Allocation Support',
    badge: 'Senior Advisory',
    description: 'Experienced macro-asset directors standing by to guide offshore holdings, bonds, and venture capital syndicates.',
    category: 'support',
    bgImage: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#f43f5e',
    cta: 'Request Review',
    link: '/advisor'
  },
  {
    id: 'asset-support-8',
    title: 'International Advisory Session',
    subTitle: 'Multi-Currency Account Support',
    badge: 'Compliance Desk',
    description: 'Resolve high-priority deposit delays, tax withholding documents, and foreign transaction clearance approvals.',
    category: 'support',
    bgImage: 'https://images.unsplash.com/photo-1580894732444-8febeb78ec3e?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#14b8a6',
    cta: 'Call Desk',
    link: '/messages'
  },
  {
    id: 'asset-support-9',
    title: 'Private Wealth Brainstorm',
    subTitle: 'Family Trust Asset Re-allocation',
    badge: 'Advisory Unit',
    description: 'Personalized wealth transition plans matching family inheritances with modern global trust rules.',
    category: 'support',
    bgImage: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#4f46e5',
    cta: 'Schedule Brainstorm',
    link: '/advisor'
  },
  {
    id: 'asset-support-10',
    title: 'Customer Relations Concierge',
    subTitle: 'Warm Executive Liaison Desk',
    badge: 'VIP Concierge',
    description: 'Highly trained private concierge team catering to travel, credit, and high-capital real-world bookings.',
    category: 'support',
    bgImage: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#d97706',
    cta: 'Call Concierge',
    link: '/messages'
  },
  {
    id: 'asset-support-11',
    title: 'Advisory Coffee Council',
    subTitle: 'Personal Wealth Structuring Session',
    badge: 'Casual Wealth',
    description: 'Casual elite consultancy to review active yield performance, real estate investments, and asset allocations.',
    category: 'support',
    bgImage: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#3b82f6',
    cta: 'Coffee Booking',
    link: '/advisor'
  },
  {
    id: 'asset-support-12',
    title: 'Multi-lingual Support Lead',
    subTitle: 'Global Client Coordinator Desk',
    badge: 'Global Outreach',
    description: 'Immediate coordination on transfers originating from the European Union, Asia-Pacific, and Americas.',
    category: 'support',
    bgImage: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#10b981',
    cta: 'Contact Coordinator',
    link: '/messages'
  },
  {
    id: 'asset-support-13',
    title: 'Sovereign Priority Support',
    subTitle: 'Dedicated Wealth Desk Lead',
    badge: 'Top Tier Priority',
    description: 'Strict 1-minute callback response for clients with aggregate ledger holdings exceeding $1,000,000.',
    category: 'support',
    bgImage: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#fbbf24',
    cta: 'Access Priority Desk',
    link: '/messages'
  },
  {
    id: 'asset-support-14',
    title: 'Accounts Success Partner',
    subTitle: 'Direct Business Banking Support',
    badge: 'Enterprise Desk',
    description: 'Resolve high-value invoice clearances, payroll allocations, dynamic corporate lines, and asset audits.',
    category: 'support',
    bgImage: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#38bdf8',
    cta: 'Call Enterprise Desk',
    link: '/messages'
  },
  {
    id: 'asset-support-15',
    title: 'Sovereign Concierge Welcome',
    subTitle: 'Elite Client Host Desk',
    badge: 'Greeting Unit',
    description: 'Welcome hosts ready to usher accredited high-value clients into our private high-rise meeting lounges.',
    category: 'support',
    bgImage: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#ca8a04',
    cta: 'Book Zurich Entry',
    link: '/messages'
  },
  {
    id: 'asset-support-16',
    title: 'Private Advisory Dialogue',
    subTitle: 'Interactive Portfolio Overviews',
    badge: 'Live Session',
    description: 'Virtual and physical private briefings presenting newly authorized investment portfolios and dividend structures.',
    category: 'support',
    bgImage: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#6366f1',
    cta: 'Schedule Dialogue',
    link: '/advisor'
  },
  {
    id: 'asset-support-17',
    title: 'Elite Support Desk Director',
    subTitle: 'Global Operations Coordination',
    badge: 'Escalation Node',
    description: 'Senior management intervention for immediate sovereign limit extensions and complex cross-border clearance.',
    category: 'support',
    bgImage: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#ef4444',
    cta: 'Direct Escalation',
    link: '/messages'
  },

  // CATEGORY: OFFICES (Institutional Offices & Skyscraper HQ) - 16 assets
  {
    id: 'asset-offices-1',
    title: 'Zurich Skyscraper HQ',
    subTitle: 'Sovereign Wealth Tower',
    badge: 'Global HQ',
    description: 'The futuristic high-rise headquarters controlling the unified sovereign wealth ledger network and global trust bays.',
    category: 'offices',
    bgImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#1e293b',
    cta: 'Corporate Overview',
    link: '/summary'
  },
  {
    id: 'asset-offices-2',
    title: 'Modern Financial District',
    subTitle: 'Global Capital Center',
    badge: 'Banking Nexus',
    description: 'Direct integration nodes spanning global financial capitals to execute trade routing and secure real estate acquisitions.',
    category: 'offices',
    bgImage: 'https://images.unsplash.com/photo-1449157291145-7efd050a4d0e?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#475569',
    cta: 'Explore Nodes',
    link: '/summary'
  },
  {
    id: 'asset-offices-3',
    title: 'Canary Wharf Trade Hub',
    subTitle: 'London Sterling Reserves',
    badge: 'UK Exchange',
    description: 'High-speed institutional ledger clearing lines nestled in London Canary Wharf to manage European currency blocks.',
    category: 'offices',
    bgImage: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#334155',
    cta: 'View Clearing',
    link: '/summary'
  },
  {
    id: 'asset-offices-4',
    title: 'Wall Street Central Bay',
    subTitle: 'New York Escrow Center',
    badge: 'US Reserve',
    description: 'Corporate US Dollar settlement gates and legal compliance registries backed by New York securities routing.',
    category: 'offices',
    bgImage: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#0f172a',
    cta: 'USD Settlement Desk',
    link: '/summary'
  },
  {
    id: 'asset-offices-5',
    title: 'Lobby Glass Escalator',
    subTitle: 'Sovereign Bank Atrium',
    badge: 'Elevated Atrium',
    description: 'Premium architectural waiting atrium with real-time currency ticker feeds and private customer greeting desk.',
    category: 'offices',
    bgImage: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#10b981',
    cta: 'Tour Atrium',
    link: '/summary'
  },
  {
    id: 'asset-offices-6',
    title: 'Futuristic Boardroom Bay',
    subTitle: 'Strategic Syndicate Chamber',
    badge: 'Chamber Vault',
    description: 'Equipped with end-to-end encrypted video link arrays connecting sovereign wealth funds and accredited buyouts.',
    category: 'offices',
    bgImage: 'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#3b82f6',
    cta: 'Book Chamber',
    link: '/messages'
  },
  {
    id: 'asset-offices-7',
    title: 'Modern Glass Dome HQ',
    subTitle: 'Financial Research Center',
    badge: 'Research Node',
    description: 'Advanced asset research hub analyzing global yields, macro-hedges, alternative assets, and digital tokens.',
    category: 'offices',
    bgImage: 'https://images.unsplash.com/photo-1519500093361-90ac391453fc?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#84cc16',
    cta: 'Access Research',
    link: '/summary'
  },
  {
    id: 'asset-offices-8',
    title: 'Premium Reception Suite',
    subTitle: 'Sovereign Elite Lounge Entrance',
    badge: 'Sovereign Lounge',
    description: 'Stunning reception suite featuring bespoke luxury architecture, premium client hosts, and biometric security gates.',
    category: 'offices',
    bgImage: 'https://images.unsplash.com/photo-1556761175-4b46a572b786?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#eab308',
    cta: 'Lounge Schedule',
    link: '/messages'
  },
  {
    id: 'asset-offices-9',
    title: 'Singapore Finance Tower',
    subTitle: 'Asia-Pacific Settlement Hub',
    badge: 'APAC Node',
    description: 'Corporate settlement gateway operating high-capacity ledger pools across Singapore and East Asian markets.',
    category: 'offices',
    bgImage: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#ec4899',
    cta: 'View APAC Pool',
    link: '/summary'
  },
  {
    id: 'asset-offices-10',
    title: 'Swiss Alps Vault HQ',
    subTitle: 'Bunker Treasury Vault',
    badge: 'Mountain Bunker',
    description: 'Deep physical bullion deposit lockers and secure hardware servers constructed underneath the Swiss Alps.',
    category: 'offices',
    bgImage: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#0ea5e9',
    cta: 'Vault Verification',
    link: '/settings'
  },
  {
    id: 'asset-offices-11',
    title: 'Sovereign Glass Façade',
    subTitle: 'Modernist Zurich Main Office',
    badge: 'Main Office',
    description: 'Uncompromising corporate office providing premium private banking and elite family fund trusts.',
    category: 'offices',
    bgImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#6366f1',
    cta: 'Main Desk Portal',
    link: '/summary'
  },
  {
    id: 'asset-offices-12',
    title: 'Elite Banking Entrance',
    subTitle: 'Zurich Offshore Private Club',
    badge: 'Elite Private Club',
    description: 'An elegant high-status private compound strictly open to accredited partners and certified sovereign family offices.',
    category: 'offices',
    bgImage: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#a855f7',
    cta: 'Club Access',
    link: '/messages'
  },
  {
    id: 'asset-offices-13',
    title: 'Tokyo Shinjuku Skyline',
    subTitle: 'Japan Yen Liquidity Depot',
    badge: 'Yen Liquidity',
    description: 'High-speed Tokyo settlement networks connecting institutional liquidity reserves across Asian central banks.',
    category: 'offices',
    bgImage: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#f43f5e',
    cta: 'Yen Reserves Ledger',
    link: '/summary'
  },
  {
    id: 'asset-offices-14',
    title: 'High-rise Executive Atrium',
    subTitle: 'Canary Wharf High Floor Lounge',
    badge: 'High Lounge',
    description: 'Spectacular executive atrium with stunning negative space layouts reserved for deep negotiation sessions.',
    category: 'offices',
    bgImage: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#14b8a6',
    cta: 'Lounge Access',
    link: '/messages'
  },
  {
    id: 'asset-offices-15',
    title: 'Manhattan Private Helipad',
    subTitle: 'Wall Street Transit Node',
    badge: 'Express Transit',
    description: 'Instant heli-shuttle transit coordinates connecting JFK Airport with our Wall Street primary executive offices.',
    category: 'offices',
    bgImage: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#3b82f6',
    cta: 'Schedule Transit',
    link: '/messages'
  },
  {
    id: 'asset-offices-16',
    title: 'Security Vault lobby',
    subTitle: 'Double-Locked Vault Access',
    badge: 'Gold lobby',
    description: 'Vetted armored personnel guarding entrance gates leading to deep physical cash and gold brick vaults.',
    category: 'offices',
    bgImage: 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#06b6d4',
    cta: 'Enter Vault Lobby',
    link: '/settings'
  },

  // CATEGORY: SECURITY (Insurance, Security & Risk Protection) - 16 assets
  {
    id: 'asset-security-1',
    title: 'Multi-Sig Ledger Vault',
    subTitle: 'Hardware Key Secure Ledger',
    badge: 'Cold Storage Only',
    description: 'Military-grade hardware security modules (HSM) guarding client wealth vectors with offline multi-sig rules.',
    category: 'security',
    bgImage: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#10b981',
    cta: 'Active Cold Vault',
    link: '/settings'
  },
  {
    id: 'asset-security-2',
    title: 'Cyber Security Operations',
    subTitle: 'Secure Transaction Monitoring',
    badge: 'SHA-512 Matrix',
    description: 'Dynamic intrusion detection panels filtering outgoing SWIFT transfers and scanning file uploads for compliance blocks.',
    category: 'security',
    bgImage: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#6366f1',
    cta: 'Audit Firewall',
    link: '/settings'
  },
  {
    id: 'asset-security-3',
    title: 'Seal of Escrow Authority',
    subTitle: 'Fully Bonded Trust Escrow',
    badge: 'Escrow Bonded',
    description: 'Independent legal registry backing multi-million dollar business transfers with certified third-party bonds.',
    category: 'security',
    bgImage: 'https://images.unsplash.com/photo-1450223709380-40570cced899?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#a855f7',
    cta: 'Inspect Escrow',
    link: '/summary'
  },
  {
    id: 'asset-security-4',
    title: 'Compliance & Audit Lead',
    subTitle: 'Global Trust Standards Officer',
    badge: 'SCC Oversight',
    description: 'Experienced compliance desk director analyzing user registration forms and verifying class-V VIP certifications.',
    category: 'security',
    bgImage: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#eab308',
    cta: 'Contact Auditor',
    link: '/advisor'
  },
  {
    id: 'asset-security-5',
    title: 'Mainframe Datacenter Vaults',
    subTitle: 'Redundant Server arrays',
    badge: 'Hardware Nodes',
    description: 'High-integrity secure enterprise clusters with complete physical isolation shields and biometric keylocks.',
    category: 'security',
    bgImage: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#ec4899',
    cta: 'Server Status',
    link: '/settings'
  },
  {
    id: 'asset-security-6',
    title: 'Sovereign Insurance Audit',
    subTitle: 'Institutional Asset Insurance Pool',
    badge: 'Asset Insured',
    description: 'Independent coverage contracts protecting digital wealth assets, real estate holdings, and bullion reserves.',
    category: 'security',
    bgImage: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#3b82f6',
    cta: 'View Coverage',
    link: '/settings'
  },
  {
    id: 'asset-security-7',
    title: 'Biometric Firewall scan',
    subTitle: 'Personal Security Scan',
    badge: 'Facial & Fingerprint',
    description: 'Zero-knowledge biometric confirmation gates guarding client login access and large outbound transfers.',
    category: 'security',
    bgImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#ef4444',
    cta: 'Enroll Biometrics',
    link: '/settings'
  },
  {
    id: 'asset-security-8',
    title: 'Elite Fort Knox Vault Door',
    subTitle: 'Deep Sovereign Safe Bay',
    badge: 'Physical Vault',
    description: 'Multi-layered physical steel lock gates preventing physical penetration or unauthorized entrance to bullion reserves.',
    category: 'security',
    bgImage: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#14b8a6',
    cta: 'Enter Safe Portal',
    link: '/settings'
  },
  {
    id: 'asset-security-9',
    title: 'Sovereign Trust Seal',
    subTitle: 'Government Approved Certificate',
    badge: 'Trust Certification',
    description: 'Fully authorized corporate trust seals backing business bank accounts with triple-audit legal protection.',
    category: 'security',
    bgImage: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#38bdf8',
    cta: 'Audit Certificate',
    link: '/settings'
  },
  {
    id: 'asset-security-10',
    title: 'Cybersecurity Firewall Atrium',
    subTitle: 'Encrypted Routing Network Shield',
    badge: 'Active Shield',
    description: 'Continuous defense networks analyzing transaction metadata, routing codes, and recipient banking credentials.',
    category: 'security',
    bgImage: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#6366f1',
    cta: 'Activate Shield',
    link: '/settings'
  },
  {
    id: 'asset-security-11',
    title: 'Compliance Ledger Log',
    subTitle: 'Dynamic Transaction Verification',
    badge: 'Audit Trail',
    description: 'Unyielding historical logs storing transaction hashes, routing codes, and administrator compliance signatures.',
    category: 'security',
    bgImage: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#f43f5e',
    cta: 'Inspect Logs',
    link: '/settings'
  },
  {
    id: 'asset-security-12',
    title: 'Premium Risk Policy Paper',
    subTitle: 'Complete Sovereign Asset Protection',
    badge: 'Risk Insured',
    description: 'Legally certified financial indemnity structures protecting corporations from cyber threats or currency market swings.',
    category: 'security',
    bgImage: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#10b981',
    cta: 'Audit Policy',
    link: '/settings'
  },
  {
    id: 'asset-security-13',
    title: 'Fingerprint Biometrics Node',
    subTitle: 'Certified Hardware Authentication Key',
    badge: 'Keylock active',
    description: 'Encrypted local key exchange loops protecting high-net-worth payouts with certified touch id loops.',
    category: 'security',
    bgImage: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#ec4899',
    cta: 'Register Touch Key',
    link: '/settings'
  },
  {
    id: 'asset-security-14',
    title: 'Private Escrow Server Node',
    subTitle: 'Decentralized Blockchain Network Grid',
    badge: 'Escrow Nodes',
    description: 'High-throughput secure database nodes maintaining accurate record logs without exposure to public web servers.',
    category: 'security',
    bgImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#a855f7',
    cta: 'Sync Escrow Nodes',
    link: '/settings'
  },
  {
    id: 'asset-security-15',
    title: 'Platinum Vault Bullion Bars',
    subTitle: 'Physical Metals Custody Depot',
    badge: 'Custodial metals',
    description: 'Temperature and moisture controlled storage lockers for platinum bullion bricks, diamond crates and precious legal titles.',
    category: 'security',
    bgImage: 'https://images.unsplash.com/photo-1610375461246-83df859d8222?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#ca8a04',
    cta: 'metals Ledger',
    link: '/settings'
  },
  {
    id: 'asset-security-16',
    title: 'Real-Time Compliance Screening',
    subTitle: 'Instant Outgoing Wire Screening',
    badge: 'Screening Desk',
    description: 'Authorized supervisor panels confirming routing codes, SWIFT codes, identity forms, and legal clearance codes.',
    category: 'security',
    bgImage: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#fbbf24',
    cta: 'Open Compliance Desk',
    link: '/advisor'
  },

  // CATEGORY: CORPORATE (Corporate Finance & Investment Ledger) - 17 assets
  {
    id: 'asset-corporate-1',
    title: 'Yield Curve Analytics',
    subTitle: 'Macro Asset Performance',
    badge: 'Portfolio Trends',
    description: 'High-end investment tracking metrics compiling asset class performance, dividends, and multi-currency payouts.',
    category: 'corporate',
    bgImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#6366f1',
    cta: 'Analyze Yield',
    link: '/summary'
  },
  {
    id: 'asset-corporate-2',
    title: 'Real-Time Stock Analytics',
    subTitle: 'Sovereign Wealth Equity Ledger',
    badge: 'Global Markets',
    description: 'Dedicated financial overview of international stock markets, private company shares, and venture capital allocations.',
    category: 'corporate',
    bgImage: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#10b981',
    cta: 'Watch Stocks',
    link: '/summary'
  },
  {
    id: 'asset-corporate-3',
    title: 'Forex Arbitrage Panel',
    subTitle: 'Sovereign Multi-Currency Exchange',
    badge: 'Forex Reserve',
    description: 'Real-time multi-currency exchange feeds offering riskless arbitrage opportunities on currency gaps.',
    category: 'corporate',
    bgImage: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#3b82f6',
    cta: 'Trade Forex',
    link: '/settings'
  },
  {
    id: 'asset-corporate-4',
    title: 'Corporate Mergers Lead',
    subTitle: 'Acquisitions & Buyouts Coordinator',
    badge: 'M&A Advisors',
    description: 'Direct advisory desk organizing leveraged corporate buyouts, stock redistributions, and asset combinations.',
    category: 'corporate',
    bgImage: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#ca8a04',
    cta: 'Call Mergers Team',
    link: '/advisor'
  },
  {
    id: 'asset-corporate-5',
    title: 'Currency Trading Desk',
    subTitle: 'Institutional Liquidity Exchange',
    badge: 'Bond Markets',
    description: 'High-speed institutional ledger terminals to trade government bonds, corporate bonds, and stable currencies.',
    category: 'corporate',
    bgImage: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#0ea5e9',
    cta: 'Exchange Ledger',
    link: '/summary'
  },
  {
    id: 'asset-corporate-6',
    title: 'Liquid Assets Allocation',
    subTitle: 'Venture Capital Board meeting',
    badge: 'Seed Investment',
    description: 'Elite panel meetings reviewing newly authorized loans, venture seed funding, and portfolio structures.',
    category: 'corporate',
    bgImage: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#a855f7',
    cta: 'Request Session',
    link: '/messages'
  },
  {
    id: 'asset-corporate-7',
    title: 'Corporate Bond Ledger',
    subTitle: 'Institutional Sovereign Debts',
    badge: 'Deeds & Trusts',
    description: 'Structured debt accounts generating passive, low-risk yields backed by stable government tax collections.',
    category: 'corporate',
    bgImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#14b8a6',
    cta: 'Buy corporate Bonds',
    link: '/summary'
  },
  {
    id: 'asset-corporate-8',
    title: 'Sovereign Portfolio Growth',
    subTitle: 'Generational Wealth Dashboard',
    badge: 'Wealth Evolution',
    description: 'Interactive analytics ledger recording account balances, historical gains, escrow funds, and dividend cycles.',
    category: 'corporate',
    bgImage: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#ec4899',
    cta: 'Growth Metrics',
    link: '/summary'
  },
  {
    id: 'asset-corporate-9',
    title: 'Global Syndicate Review',
    subTitle: 'Pre-IPO Corporate buyouts',
    badge: 'Joint Venture',
    description: 'Coordinated funding pools aligning corporate lines to invest in tomorrow\'s technological leaders.',
    category: 'corporate',
    bgImage: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#f43f5e',
    cta: 'Venture Catalog',
    link: '/summary'
  },
  {
    id: 'asset-corporate-10',
    title: 'Arbitrage Strategy Terminal',
    subTitle: 'Cross-Border Exchange Trading',
    badge: 'Forex Matrix',
    description: 'Automated high-frequency exchange terminals exploiting fractional pricing differences in global currency nodes.',
    category: 'corporate',
    bgImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#84cc16',
    cta: 'Arbitrage Setup',
    link: '/settings'
  },
  {
    id: 'asset-corporate-11',
    title: 'Forex Hedging Grid',
    subTitle: 'Institutional Currency Protection',
    badge: 'Forex Insurance',
    description: 'Establish currency hedging derivative pools protecting your assets from inflation and geopolitical fluctuations.',
    category: 'corporate',
    bgImage: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#6366f1',
    cta: 'Open Hedging Desk',
    link: '/settings'
  },
  {
    id: 'asset-corporate-12',
    title: 'Corporate Trust Account',
    subTitle: 'High-Yield Liquidity Savings',
    badge: 'Asset Trust',
    description: 'Favorable interest rate savings accounts specifically designed for corporate liquidity reserves.',
    category: 'corporate',
    bgImage: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#10b981',
    cta: 'Apply High-Yield',
    link: '/summary'
  },
  {
    id: 'asset-corporate-13',
    title: 'Venture Capital Allocations',
    subTitle: 'Billion Dollar Private Equity Funding',
    badge: 'Syndicate Capital',
    description: 'Provide venture financing to pre-vetted corporate buyouts, real estate syndicates, and raw resource mines.',
    category: 'corporate',
    bgImage: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#0ea5e9',
    cta: 'View Allocations',
    link: '/summary'
  },
  {
    id: 'asset-corporate-14',
    title: 'Liquid Asset Operations',
    subTitle: 'Corporate Dividend Distribution planning',
    badge: 'Dividend Plan',
    description: 'Establish automated, tax-sheltered dividend settlement setups distributing returns to family heirs.',
    category: 'corporate',
    bgImage: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#a855f7',
    cta: 'Plan Dividends',
    link: '/settings'
  },
  {
    id: 'asset-corporate-15',
    title: 'Multi-Currency Settlement Ledger',
    subTitle: 'Global Settlement Ledger Analytics',
    badge: 'Global Ledger',
    description: 'Complete dashboard documenting SWIFT clearances, crypto payments, euro transfers and trade allocations.',
    category: 'corporate',
    bgImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#ec4899',
    cta: 'Open Settlement Ledger',
    link: '/summary'
  },
  {
    id: 'asset-corporate-16',
    title: 'Digital Wealth Custody Trust',
    subTitle: 'Secured Cryptographic Reserves',
    badge: 'Digital Custody',
    description: 'Deploy insured digital ledger storage containing Bitcoin, Ethereum, and corporate stable coins.',
    category: 'corporate',
    bgImage: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#eab308',
    cta: 'Open Crypto Trust',
    link: '/summary'
  },
  {
    id: 'asset-corporate-17',
    title: 'Sovereign Syndicate Boardroom',
    subTitle: 'Accredited Sovereign Syndicate Sessions',
    badge: 'Syndicate Advisory',
    description: 'Schedule corporate board negotiations locking joint credit buyouts with leading international banks.',
    category: 'corporate',
    bgImage: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=1200&auto=format&fit=crop',
    hexColor: '#f43f5e',
    cta: 'Request Session',
    link: '/messages'
  },

  // CATEGORY: VIDEOS (Dynamic High-Definition Video Loops) - 16 assets
  {
    id: 'asset-video-1',
    title: 'Sovereign Cash Reserve Loop',
    subTitle: 'Physical Dollar Stack Loop',
    badge: 'Live Video',
    description: 'High-definition video loop featuring physical stacks of freshly bound corporate US Dollar banknotes.',
    category: 'videos',
    bgImage: 'https://assets.mixkit.co/videos/preview/mixkit-stack-of-one-hundred-dollar-bills-39907-large.mp4',
    hexColor: '#10b981',
    cta: 'View Video Loop',
    link: '/summary'
  },
  {
    id: 'asset-video-2',
    title: 'Bank Dollar Counting Machine',
    subTitle: 'Automatic Cash Velocity Loop',
    badge: 'Live Video',
    description: 'Realistic video loop showcasing high-speed currency counters sorting gold-certificate dollar notes.',
    category: 'videos',
    bgImage: 'https://assets.mixkit.co/videos/preview/mixkit-counting-one-hundred-dollar-bills-close-up-39906-large.mp4',
    hexColor: '#d97706',
    cta: 'velocity Dashboard',
    link: '/summary'
  },
  {
    id: 'asset-video-3',
    title: 'Abstract High-Tech Networks',
    subTitle: 'SHA-512 Escrow Routing Loop',
    badge: 'Live Video',
    description: 'Glowing futuristic vector link grids executing digital escrow payouts and ledger synchronization.',
    category: 'videos',
    bgImage: 'https://assets.mixkit.co/videos/preview/mixkit-abstract-technology-network-connection-background-3134-large.mp4',
    hexColor: '#4f46e5',
    cta: 'Inspect Networks',
    link: '/settings'
  },
  {
    id: 'asset-video-4',
    title: 'Cyber Safe Hud Interface',
    subTitle: 'Security Block Ledger Loop',
    badge: 'Live Video',
    description: 'Advanced scifi military dashboard tracking secure server coordinates and biometric firewalls.',
    category: 'videos',
    bgImage: 'https://assets.mixkit.co/videos/preview/mixkit-hud-interface-system-analyzing-screen-3195-large.mp4',
    hexColor: '#a855f7',
    cta: 'Secure System',
    link: '/settings'
  },
  {
    id: 'asset-video-5',
    title: 'Blue Mainframe Led Flashes',
    subTitle: 'Cold Vault Server Redundancy',
    badge: 'Live Video',
    description: 'Flashing core servers nested in highly secure, temperature controlled banking datacenters.',
    category: 'videos',
    bgImage: 'https://assets.mixkit.co/videos/preview/mixkit-blue-led-lights-flashing-on-servers-34329-large.mp4',
    hexColor: '#0284c7',
    cta: 'Server Logs',
    link: '/settings'
  },
  {
    id: 'asset-video-6',
    title: 'Global World Trade Loop',
    subTitle: 'Cross-Border Capital Movements',
    badge: 'Live Video',
    description: 'Interactive map displaying international wire transfers and offshore dividend allocations in real-time.',
    category: 'videos',
    bgImage: 'https://assets.mixkit.co/videos/preview/mixkit-digital-world-map-network-connection-background-3135-large.mp4',
    hexColor: '#0ea5e9',
    cta: 'International Map',
    link: '/summary'
  },
  {
    id: 'asset-video-7',
    title: 'Robotic Security Scan',
    subTitle: 'Secure Biometric Validation',
    badge: 'Live Video',
    description: 'High-tech facial and grid scanning process confirming administrator credentials for high-net-worth actions.',
    category: 'videos',
    bgImage: 'https://assets.mixkit.co/videos/preview/mixkit-robotic-security-scanning-system-background-3140-large.mp4',
    hexColor: '#ec4899',
    cta: 'Biometrics Panel',
    link: '/settings'
  },
  {
    id: 'asset-video-8',
    title: 'Tech System Analytics HUD',
    subTitle: 'Real-Time FX Hedging Tickers',
    badge: 'Live Video',
    description: 'Moving graphical coordinate bars monitoring stock indexes, treasury rates, arbitrage gains and yields.',
    category: 'videos',
    bgImage: 'https://assets.mixkit.co/videos/preview/mixkit-technical-charts-graphs-hud-scifi-3194-large.mp4',
    hexColor: '#10b981',
    cta: 'Open Ticker Board',
    link: '/summary'
  },
  {
    id: 'asset-video-9',
    title: 'Cyber gold Lock Scanning',
    subTitle: 'Escrow Multi-Sig Lock Loop',
    badge: 'Live Video',
    description: 'Bespoke high-contrast gold lock scanning dashboard securing capital assets with deep cryptographical proofs.',
    category: 'videos',
    bgImage: 'https://assets.mixkit.co/videos/preview/mixkit-hud-lock-icon-scanning-for-verification-3200-large.mp4',
    hexColor: '#eab308',
    cta: 'Inspect Lock',
    link: '/settings'
  },
  {
    id: 'asset-video-10',
    title: 'Sovereign City Night Drone',
    subTitle: 'Canary Wharf High View Night Loop',
    badge: 'Live Video',
    description: 'Stunning high-angle helicopter video sweep over a modern metropolis, representing global empire growth.',
    category: 'videos',
    bgImage: 'https://assets.mixkit.co/videos/preview/mixkit-aerial-timelapse-of-a-modern-city-at-night-23374-large.mp4',
    hexColor: '#38bdf8',
    cta: 'City Coordinates',
    link: '/summary'
  },
  {
    id: 'asset-video-11',
    title: 'Biometric Face Scan Hud',
    subTitle: 'Zero-Knowledge VIP verification',
    badge: 'Live Video',
    description: 'Cyberpunk biometric identity verification loops validating secure elite user profiles.',
    category: 'videos',
    bgImage: 'https://assets.mixkit.co/videos/preview/mixkit-face-recognition-scanning-cyberpunk-process-3198-large.mp4',
    hexColor: '#f43f5e',
    cta: 'Scan Face ID',
    link: '/settings'
  },
  {
    id: 'asset-video-12',
    title: 'Soaring Over Skyscrapers',
    subTitle: 'Skyscraper Office Sweep Drone',
    badge: 'Live Video',
    description: 'Breathtaking high-fidelity drone path gliding through reflecting glass skyscraper peaks in corporate districts.',
    category: 'videos',
    bgImage: 'https://assets.mixkit.co/videos/preview/mixkit-soaring-over-skyscrapers-3121-large.mp4',
    hexColor: '#64748b',
    cta: 'View Skyscraper Peak',
    link: '/summary'
  },
  {
    id: 'asset-video-13',
    title: 'Abstract Matrix Code Lines',
    subTitle: 'Direct Ledger Stream Sweep',
    badge: 'Live Video',
    description: 'Neon glowing cryptographic matrix codes sweeping downwards, symbolizing complete transaction security.',
    category: 'videos',
    bgImage: 'https://assets.mixkit.co/videos/preview/mixkit-abstract-technology-matrix-elements-scifi-3133-large.mp4',
    hexColor: '#059669',
    cta: 'Ledger Flow',
    link: '/settings'
  },
  {
    id: 'asset-video-14',
    title: 'Rotating Wireframe Globe Grid',
    subTitle: 'Multi-Capital Branch Routing Grid',
    badge: 'Live Video',
    description: 'Encrypted global routing nodes executing cross-border escrow payments in real-time.',
    category: 'videos',
    bgImage: 'https://assets.mixkit.co/videos/preview/mixkit-rotating-world-communication-lines-technology-background-3136-large.mp4',
    hexColor: '#3b82f6',
    cta: 'Global Branches Network',
    link: '/summary'
  },
  {
    id: 'asset-video-15',
    title: 'Shield Firewall Analytics Hud',
    subTitle: 'Sovereign Shield Protection loop',
    badge: 'Live Video',
    description: 'Advanced dynamic scifi security shield scanning systems keeping hackers and compliance locks completely safe.',
    category: 'videos',
    bgImage: 'https://assets.mixkit.co/videos/preview/mixkit-shield-icon-system-protection-scifi-analytics-3199-large.mp4',
    hexColor: '#ef4444',
    cta: 'Verify Firewall',
    link: '/settings'
  },
  {
    id: 'asset-video-16',
    title: 'Vault Datacenter Rack Sweep',
    subTitle: 'Secure Financial Data Cabinets Sweep',
    badge: 'Live Video',
    description: 'Industrial sweep through glowing green security server boxes executing core microtransactions and escrow transfers.',
    category: 'videos',
    bgImage: 'https://assets.mixkit.co/videos/preview/mixkit-inside-a-datacenter-server-racks-and-cooling-34327-large.mp4',
    hexColor: '#10b981',
    cta: 'Verify Cabinets Nodes',
    link: '/settings'
  },
  // NEW HIGH-RES INSTITUTIONAL BANKING ASSETS
  {
    id: 'asset-atm-safety-1',
    title: 'ATM Safety & Precautions Terminal',
    subTitle: 'Global Dispense Network',
    badge: 'Surcharge Free',
    description: 'Secure ATM cash dispatch with active skimming protection and biometric verification.',
    category: 'security',
    bgImage: 'https://www.housingfinance.co.ug/wp-content/uploads/2022/11/hfb-Safety-precautions-at-the-ATM-1024x768.jpg',
    hexColor: '#10b981',
    cta: 'Locate ATM',
    link: '/atm-locator'
  },
  {
    id: 'asset-atm-node-2',
    title: 'Follow My Vote Point-of-Sale',
    subTitle: 'Electronic Cashier Terminal',
    badge: 'POS Terminal',
    description: 'Universal card acceptance and multi-currency point-of-sale merchant terminals.',
    category: 'security',
    bgImage: 'https://cdn.guardian.ng/wp-content/uploads/2017/02/ATM-follow-my-vote.jpg',
    hexColor: '#3b82f6',
    cta: 'View Terminals',
    link: '/atm-locator'
  },
  {
    id: 'asset-corporate-dubai-1',
    title: 'Dubai & UAE Business Incorporation Hub',
    subTitle: 'Gulf Sovereign Gateway',
    badge: 'Zero Corporate Tax',
    description: 'Turnkey commercial banking setups, company formation, and tax residency in Dubai.',
    category: 'corporate',
    bgImage: 'https://smartzone.ae/wp-content/uploads/2026/02/Can-Foreigners-Start-a-Business-in-Dubai.jpg',
    hexColor: '#D4AF37',
    cta: 'Open Dubai Hub',
    link: '/settings'
  },
  {
    id: 'asset-temenos-interbank-1',
    title: 'Temenos Digital Interbank Core',
    subTitle: 'High-Velocity Settlement',
    badge: 'Real-time ISO-20022',
    description: 'Next-generation cloud banking architecture facilitating instant international wire routing.',
    category: 'corporate',
    bgImage: 'https://www.temenos.com/wp-content/uploads/2025/04/Temenos-digital-banking-scaled.jpg',
    hexColor: '#6366f1',
    cta: 'Audit Core',
    link: '/summary'
  },
  {
    id: 'asset-retail-comm-1',
    title: 'Retail & Commercial Banking Synergy',
    subTitle: 'Dual Tier Capital Facilities',
    badge: 'Commercial Credit',
    description: 'Comprehensive financial services spanning everyday retail banking to large-scale corporate liquidity.',
    category: 'offices',
    bgImage: 'https://www.theforage.com/blog/wp-content/uploads/2023/05/what-explains-the-difference-between-retail-and-commercial-banking-1-1024x768.jpg',
    hexColor: '#0ea5e9',
    cta: 'Explore Facilities',
    link: '/loans'
  },
  {
    id: 'asset-invest-bank-1',
    title: 'Investopedia Capital Underwriting',
    subTitle: 'Investment Banking Group',
    badge: 'M&A Advisory',
    description: 'Syndicated debt underwriting, structured investment funds, and institutional equity operations.',
    category: 'wealth',
    bgImage: 'https://www.investopedia.com/thmb/jkQJy7DLbDtBqS-odz8YW8vFTq8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/investmentbank-final-1bbd4ca5d3904dbba5b8b8b19d7d65b8.jpg',
    hexColor: '#8b5cf6',
    cta: 'Access Desk',
    link: '/advisor'
  },
  {
    id: 'asset-bnp-partner-1',
    title: 'BNP Paribas Institutional Syndicate',
    subTitle: 'Cross-Border Joint Ventures',
    badge: 'Tier-1 Alliance',
    description: 'Global joint venture financing, infrastructure lending, and multinational credit facilities.',
    category: 'corporate',
    bgImage: 'https://personal-finance.bnpparibas/app/uploads/sites/4/2024/11/starting-partnership-2023-11-27-05-27-01-utc-scaled.jpg',
    hexColor: '#059669',
    cta: 'Review Alliance',
    link: '/settings'
  }
];
